export type Field={key:string;label:string;type?:'text'|'date'|'number'|'textarea'|'select';options?:string[]};
export type Module={id:string;name:string;short:string;description:string;fields:Field[]};
const f=(key:string,label:string,type:Field['type']='text',options?:string[]):Field=>({key,label,type,options});
export const modules:Module[]=[
{id:'agreements',name:'MDA & project agreements',short:'Agreements',description:'Track clauses, proposed changes, negotiated positions and compliance.',fields:[f('agreement','Agreement / instrument'),f('clause','Article or clause'),f('obligation','Obligation or proposed wording','textarea'),f('counterparty','Responsible party'),f('evidence','Evidence reference or URL')]},
{id:'land',name:'Land & community rights',short:'Land rights',description:'Document customary claims, consultations, consent and affected communities.',fields:[f('claimType','Claim type','select',['Customary land','Resettlement','Compensation','Access','Consultation']),f('affectedGroup','Affected group'),f('parcel','Location / parcel reference'),f('consultation','Consultation record','textarea'),f('remedy','Requested remedy','textarea')]},
{id:'employment',name:'Employment commitments',short:'Employment',description:'Monitor hiring targets, job postings, actual recruitment and local participation.',fields:[f('position','Role / occupation'),f('target','Local hiring target','number'),f('actual','People hired','number'),f('employer','Employer / contractor'),f('period','Reporting period'),f('evidence','Evidence reference')]},
{id:'workforce',name:'Community workforce registry',short:'Workforce',description:'Consent-based profiles for matching residents to verified opportunities.',fields:[f('occupation','Primary trade / occupation'),f('skills','Skills and certifications','textarea'),f('experience','Years of experience','number'),f('availability','Availability','select',['Available now','Within 30 days','Not currently available']),f('contact','Contact number'),f('qualification','Qualification / license'),f('consent','Consent to share profile with prospective employers','select',['Yes','No']),f('consentDate','Consent date','date')]},
{id:'procurement',name:'Local procurement',short:'Procurement',description:'Track tender opportunities, local-content commitments and award outcomes.',fields:[f('buyer','Buyer'),f('category','Goods / services category'),f('deadline','Submission deadline','date'),f('estimatedValue','Estimated value'),f('awardee','Awardee'),f('localContent','Local-content requirement')]},
{id:'suppliers',name:'Supplier development',short:'Suppliers',description:'Map local firms, readiness gaps, training and bid participation.',fields:[f('sector','Sector'),f('registration','Business registration / tax status'),f('capacity','Products / capacity','textarea'),f('contact','Business contact'),f('readiness','Readiness','select',['Needs support','Prequalified','Bid ready']),f('support','Support needed','textarea')]},
{id:'skills',name:'Skills transfer',short:'Skills',description:'Plan training, apprenticeships, certification and placement outcomes.',fields:[f('provider','Training provider'),f('trade','Trade / course'),f('places','Seats','number'),f('startDate','Start date','date'),f('completion','Completion / certification criteria'),f('outcome','Placement outcome')]},
{id:'environment',name:'Environmental safeguards',short:'Environment',description:'Register risks, monitoring readings, incidents and corrective actions.',fields:[f('topic','Safeguard topic','select',['Water','Air / dust','Forest','Biodiversity','Waste','Tailings','Health and safety']),f('location','Site / location'),f('observation','Observation','textarea'),f('standard','Applicable standard / permit'),f('correctiveAction','Corrective action','textarea'),f('verification','Verification evidence')]},
{id:'infrastructure',name:'Corridor infrastructure',short:'Infrastructure',description:'Monitor rail, port, roads, power and shared-use commitments.',fields:[f('asset','Asset type','select',['Rail','Port','Road','Power','Water','Other']),f('route','Route / location'),f('milestone','Milestone'),f('publicAccess','Community / public access provision'),f('budget','Budget / funding'),f('evidence','Evidence reference')]},
{id:'benefits',name:'Community benefits',short:'Benefits',description:'Track funds, projects, eligibility, disbursement and delivery.',fields:[f('benefitType','Benefit type'),f('amount','Committed amount'),f('recipient','Beneficiary / community'),f('disbursement','Disbursement date','date'),f('deliverable','Deliverable / outcome'),f('proof','Payment / delivery proof')]},
{id:'grievances',name:'Grievances & remedies',short:'Grievances',description:'Log concerns, assign response, protect confidentiality and record resolution.',fields:[f('category','Category'),f('channel','Intake channel'),f('confidentiality','Confidentiality','select',['Standard','Restricted']),f('requestedRemedy','Requested remedy','textarea'),f('response','Response / action','textarea'),f('closedDate','Resolved date','date')]},
{id:'transparency',name:'Disclosure & transparency',short:'Transparency',description:'Track documents requested, publication, disclosure gaps and decisions.',fields:[f('document','Document / dataset'),f('requestDate','Request date','date'),f('holder','Document holder'),f('publication','Publication URL'),f('disclosureStatus','Disclosure status','select',['Requested','Received','Published','Withheld']),f('reason','Reason / follow-up')]},
{id:'monitoring',name:'Implementation monitoring',short:'Monitoring',description:'Inspect commitments, indicators, deadlines and independently verified progress.',fields:[f('indicator','Indicator'),f('baseline','Baseline'),f('target','Target'),f('actual','Current result'),f('period','Period'),f('verification','Verification method / source')]},
{id:'governance',name:'Council governance',short:'Governance',description:'Organize meetings, resolutions, representation and conflicts of interest.',fields:[f('meetingDate','Meeting date','date'),f('body','Committee / working group'),f('decision','Decision or resolution','textarea'),f('participants','Participants / representation'),f('conflict','Conflict declaration'),f('minutes','Minutes reference')]}
];
export const statuses=['Draft','Under review','In progress','Awaiting response','Verified','Closed'];
export const counties=['Grand Gedeh','Sinoe','River Gee','Maryland','Grand Kru','Montserrado','Other'];
